### ISSUE TITLE
Chrome flags your site as dangerous: https://controller-frontend.vercel.app/

### ISSUE THREAD

**Issue by ovizii** [giga-controller/controller#17]
Chrome says your website is dangerous.

![image](https://github.com/user-attachments/assets/bad362a2-15fb-4481-94ed-7eff7b3a860e)

**Comment by jinyang628** [comment]
> Chrome says your website is dangerous.
> 
> ![image](https://private-user-images.githubusercontent.com/837902/370709225-bad362a2-15fb-4481-94ed-7eff7b3a860e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTA2MDEsIm5iZiI6MTcyNzMxMDMwMSwicGF0aCI6Ii84Mzc5MDIvMzcwNzA5MjI1LWJhZDM2MmEyLTE1ZmItNDQ4MS05NGVkLTdlZmY3YjNhODYwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwMDI1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTM3MGY4ZDgwOGI4ZGEzNTQ5ZmU0YzA2OTViNTc0N2MyYzM1N2E2MTcwZDgzOWVkMmUyNWFkNDk0MWQzNjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KKqHn4QPp1xLWzP3LdrDsuYj_0WeGL-DXEVRiH7xYRk)

Thanks for pointing it out! This has something to do with our domain/clerk redirects. Looking into it now and will ping you when it's resolved.

**Comment by jinyang628** [comment]
Hey @ovizii 

Thank you again for flagging it out. We have rectified the issue for now and are taking careful steps to make sure our site doesn't get flagged again (by taking more precautions on authentication, how we store access tokens, personal information, etc.)

You should see that the site is whitelisted!

pls let us know if there's anything else that can be done better and we will make the fix asap

**Comment by ovizii** [comment]
Thansk for following up. I tried different PCs and cleared my cache but I still get the warning. I assume it'll take some time but thanks for following up on this. I'll check again in a few days.
